# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "doublets_scrub"
description: Module metadata for process doublets_scrub
keywords:
  - doublets_scrub
  - nextflow
  - module
tools:
  - "doublets_scrub":
      description: "Wrapper process for doublets_scrub"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - []

output:
  - []

authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
