# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "doublets_scrub"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "doublets_scrub":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null
input:
  - []
output:
  - []
authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
