# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "createhashingref"
description: Module metadata for process CREATEHASHINGREF
keywords:
  - createhashingref
  - nextflow
  - module
tools:
  - "createhashingref":
      description: "Wrapper process for CREATEHASHINGREF"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - []

output:
  - []

authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
