# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "createguideref"
description: Module metadata for process CREATEGUIDEREF
keywords:
  - createguideref
  - nextflow
  - module
tools:
  - "createguideref":
      description: "Wrapper process for CREATEGUIDEREF"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - []

output:
  - []

authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
