# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "seqspeccheck"
description: Module metadata for process SEQSPECCHECK
keywords:
  - seqspeccheck
  - nextflow
  - module
tools:
  - "seqspeccheck":
      description: "Wrapper process for SEQSPECCHECK"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - []

output:
  - []

authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
