# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "preparecovariate"
description: Module metadata for process PREPARECOVARIATE
keywords:
  - preparecovariate
  - nextflow
  - module
tools:
  - "preparecovariate":
      description: "Wrapper process for PREPARECOVARIATE"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - []

output:
  - []

authors:
  - "@cmatKhan"
maintainers:
  - "@cmatKhan"
